### ISSUE TITLE
import fails if file include dot

### ISSUE THREAD

**Issue by jeromedecoster** [reworkcss/rework-import#14]
Hi,

If you modify the `recursive` test to rename the file `foo.css` to `foo.foo.css`
https://github.com/reworkcss/rework-import/tree/master/test/fixtures/recursive

And edit the import to `@import 'foo.foo.css' (min-width: 25em);`
https://github.com/reworkcss/rework-import/blob/master/test/fixtures/recursive/index.css#L1 

The test fails because the `urlRegex().test` fails
https://github.com/reworkcss/rework-import/blob/master/index.js#L131

Because the test is too strict.

If you modify it to
```js
if (urlRegex({exact: true}).test(data.path)) {
````

All tests are passed and you can now have filename with dot

Thanks

**Comment by kevva** [comment]
Fixed in https://github.com/reworkcss/rework-import/commit/be9babbff331524ea55599ccbfc1964f4ed9ead4.
